### ISSUE TITLE
Tauntmaster Needs Update Please

### ISSUE THREAD

**Issue by tankspank** [lavjamanxd/classic-addon-fixes#3]
I appreciate your work in continuing this addon.  With the new Blizzard update, however, neither the default addon nor your updated code are working.  TM has been my go-to tanking addon since the original days of LK.  It'd be nice to see this updated for the latest WoW version.  

On a side note, would you consider taking over this addon, even if you named it something differently?

**Comment by lavjamanxd** [comment]
Heya
Sorry for the late response again, was busy irl.
If you are still playing in cataclysm, i made an update for the TauntMaster, it should be working again.

**Comment by tankspank** [comment]
Honestly, I found this out before you even sent this email, lol. 

It works wonderfully too, everything is exactly how it was back during the original days, whi h is why I love it.  When things work, and work well, don't change them.

Thank you very much for updating and keeping with the project! 

⁣Get BlueMail for Android ​
